feat: reconfigure GRUB after firmware update

diff --git a/bin/update-firmware b/bin/update-firmware
--- a/bin/update-firmware
+++ b/bin/update-firmware
@@ -8,4 +8,22 @@ if cmd-missing fwupdmgr; then
 fi
 
 fwupdmgr refresh
+
+# Update firmware - some exit codes are normal (0=success, 2=no updates available)
+# Temporarily disable set -e to handle these codes
+set +e
 sudo fwupdmgr update
+UPDATE_EXIT_CODE=$?
+set -e
+
+# After updating firmware, /boot mount may fail
+# Reconfigure GRUB to ensure it's up to date
+# Only reconfigure if update was successful (0) or no updates available (2)
+if [ $UPDATE_EXIT_CODE -eq 0 ] || [ $UPDATE_EXIT_CODE -eq 2 ]; then
+  echo
+  update-grub || {
+    echo -e "\e[33mWarning: Could not reconfigure GRUB. You may need to do it manually.\e[0m"
+  }
+elif [ $UPDATE_EXIT_CODE -ne 0 ]; then
+  echo -e "\e[33mWarning: Firmware update failed or was cancelled (exit code: $UPDATE_EXIT_CODE).\e[0m"
+fi
diff --git a/bin/update-keyring b/bin/update-keyring
--- a/bin/update-keyring
+++ b/bin/update-keyring
@@ -1,14 +1,25 @@
 #!/bin/bash
 
+set -e
+
 # Ensure we have the keyring package installed and populate it with Arch Linux master keys
-if pkg-missing keyring; then
+if pkg-missing archlinux-keyring; then
   # This is generally not a good idea, but this is a special case because we're going to be updating
   # the full set of packages in update-system-pkgs right after this (and it needs latest keyring)!
   sudo pacman -Sy
-  pkg-add keyring
+  pkg-add archlinux-keyring
 fi
 
 # Populate keyring with all Arch Linux master keys (automatically imports all necessary keys)
 # This is the standard Arch Linux method and doesn't require hardcoding specific key IDs
 # It will import all keys from the installed keyring package
-sudo pacman-key --populate archlinux
+if ! sudo pacman-key --populate archlinux 2>/dev/null; then
+  echo -e "\e[33mKeyring appears to be outdated. Attempting full recovery...\e[0m"
+  pkg-update-keyring
+else
+  # If populate worked, try updating keyring normally
+  if ! sudo pacman -Sy archlinux-keyring --noconfirm 2>/dev/null; then
+    echo -e "\e[33mError updating keyring. Attempting full recovery...\e[0m"
+    pkg-update-keyring
+  fi
+fi
